baseURL = 'https://knowledge-base-b1m.pages.dev/'
languageCode = 'zh-cn'
title = '我的个人知识库'

[module]
  [[module.imports]]
    path = 'github.com/jpanther/congo/v2'

[params]
  colorScheme = 'congo'
  defaultAppearance = 'auto'
  
  [params.homepage]
    layout = 'profile'
    showRecent = true
    
  [params.author]
    name = '661'
    headline = '正在构建我的个人知识库'
    links = [
      { icon = 'github', href = 'https://github.com/661616' },
      { icon = 'email', href = 'mailto:ygzh0525@gmail.com' }
    ]

  [params.search]
    enable = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 20
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 30
