baseURL = 'https://knowledge-base-b1m.pages.dev/'
languageCode = 'zh-cn'
title = '我的个人知识库'

[module]
[[module.imports]]
path = 'github.com/jpanther/congo/v2'

[params]
colorScheme = 'congo'
defaultAppearance = 'auto'

[params.homepage]
layout = 'profile'
showRecent = true

[params.article]
showDate = true
showReadingTime = true
showWordCount = true
showTaxonomies = true       # 显示标签和分类
showTableOfContents = true  # 显示目录
showHeadingAnchors = true   # 标题锚点链接
showAuthor = false          # 文章内不重复显示作者(首页已显示)
showBreadcrumbs = true      # 开启面包屑导航
showSeries = true           # 开启系列文章导航

[params.author]
name = '661'
headline = '正在构建我的个人知识库'

[[params.author.links]]
github = 'https://github.com/661616'

[[params.author.links]]
mail = 'mailto:ygzh0525@gmail.com'

[params.footer]
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[params.search]
enable = true

[menu]
[[menu.main]]
identifier = 'posts'
name = '文章'
url = '/posts/'
weight = 10

[[menu.main]]
identifier = 'categories'
name = '分类'
url = '/categories/'
weight = 20

[[menu.main]]
identifier = 'tags'
name = '标签'
url = '/tags/'
weight = 30

[[menu.main]]
identifier = 'life'
name = '人生版本'
url = '/life/'
weight = 15

[taxonomies]
  category = 'categories'
  tag = 'tags'
  series = 'series'  # 添加这一行